[build]
command = "pnpm build"
publish = "dist"
functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/strapi"
  status = 200
  force = true

[[redirects]]
  from = "/admin/build/*"
  to = "/dist/build/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/dist/build/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/dist/build/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "better-sqlite3",
    "@strapi/database",
    "sequelize",
    "mongoose",
    "redis",
    "koa2-ratelimit",
    "pg-hstore"
  ]

[build.environment]
NPM_FLAGS = "--no-frozen-lockfile"