[build]
command = "pnpm build"
publish = "dist"
functions = "netlify/functions"

[dev]
  command = "pnpm develop"
  targetPort = 1337
  port = 8888
  publish = "public"
  jwtSecret = "SOME-SECRET"
  jwtRoleClaim = "strapi.roles"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/strapi"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "better-sqlite3",
    "@strapi/database",
    "sequelize",
    "mongoose",
    "redis",
    "koa2-ratelimit",
    "pg-hstore"
  ]

[build.environment]
NPM_FLAGS = "--no-frozen-lockfile"