# netlify.toml
[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = ["./config/**", "./src/**"]

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"