[build]
command = "pnpm build"
publish = "dist"
functions = "netlify/functions"

[[redirects]]
  from = "/admin/*"
  to = "/build/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/strapi"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "/uploads/:splat"
  status = 200
  force = true

[functions]
  external_node_modules = [
    "better-sqlite3",
    "@strapi/database",
    "@strapi/strapi",
    "sequelize",
    "mongoose",
    "redis",
    "koa2-ratelimit",
    "pg-hstore"
  ]
  node_bundler = "esbuild"
  included_files = ["./config/**", "./src/**"]

[build.environment]
NODE_VERSION = "20"